// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  ethereum,
  JSONValue,
  TypedMap,
  Entity,
  Bytes,
  Address,
  BigInt,
} from "@graphprotocol/graph-ts";

export class Approval extends ethereum.Event {
  get params(): Approval__Params {
    return new Approval__Params(this);
  }
}

export class Approval__Params {
  _event: Approval;

  constructor(event: Approval) {
    this._event = event;
  }

  get owner(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get spender(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get id(): BigInt {
    return this._event.parameters[2].value.toBigInt();
  }
}

export class ApprovalForAll extends ethereum.Event {
  get params(): ApprovalForAll__Params {
    return new ApprovalForAll__Params(this);
  }
}

export class ApprovalForAll__Params {
  _event: ApprovalForAll;

  constructor(event: ApprovalForAll) {
    this._event = event;
  }

  get owner(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get operator(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get approved(): boolean {
    return this._event.parameters[2].value.toBoolean();
  }
}

export class MintPosition extends ethereum.Event {
  get params(): MintPosition__Params {
    return new MintPosition__Params(this);
  }
}

export class MintPosition__Params {
  _event: MintPosition;

  constructor(event: MintPosition) {
    this._event = event;
  }

  get tokenId(): BigInt {
    return this._event.parameters[0].value.toBigInt();
  }
}

export class ModifyLiquidity extends ethereum.Event {
  get params(): ModifyLiquidity__Params {
    return new ModifyLiquidity__Params(this);
  }
}

export class ModifyLiquidity__Params {
  _event: ModifyLiquidity;

  constructor(event: ModifyLiquidity) {
    this._event = event;
  }

  get tokenId(): BigInt {
    return this._event.parameters[0].value.toBigInt();
  }

  get liquidityChange(): BigInt {
    return this._event.parameters[1].value.toBigInt();
  }

  get feesAccrued(): BigInt {
    return this._event.parameters[2].value.toBigInt();
  }
}

export class Subscription extends ethereum.Event {
  get params(): Subscription__Params {
    return new Subscription__Params(this);
  }
}

export class Subscription__Params {
  _event: Subscription;

  constructor(event: Subscription) {
    this._event = event;
  }

  get tokenId(): BigInt {
    return this._event.parameters[0].value.toBigInt();
  }

  get subscriber(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class Transfer extends ethereum.Event {
  get params(): Transfer__Params {
    return new Transfer__Params(this);
  }
}

export class Transfer__Params {
  _event: Transfer;

  constructor(event: Transfer) {
    this._event = event;
  }

  get from(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get to(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get id(): BigInt {
    return this._event.parameters[2].value.toBigInt();
  }
}

export class Unsubscription extends ethereum.Event {
  get params(): Unsubscription__Params {
    return new Unsubscription__Params(this);
  }
}

export class Unsubscription__Params {
  _event: Unsubscription;

  constructor(event: Unsubscription) {
    this._event = event;
  }

  get tokenId(): BigInt {
    return this._event.parameters[0].value.toBigInt();
  }

  get subscriber(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class PositionManager__getPoolAndPositionInfoResultPoolKeyStruct extends ethereum.Tuple {
  get currency0(): Address {
    return this[0].toAddress();
  }

  get currency1(): Address {
    return this[1].toAddress();
  }

  get hooks(): Address {
    return this[2].toAddress();
  }

  get poolManager(): Address {
    return this[3].toAddress();
  }

  get fee(): i32 {
    return this[4].toI32();
  }

  get parameters(): Bytes {
    return this[5].toBytes();
  }
}

export class PositionManager__getPoolAndPositionInfoResult {
  value0: PositionManager__getPoolAndPositionInfoResultPoolKeyStruct;
  value1: BigInt;

  constructor(
    value0: PositionManager__getPoolAndPositionInfoResultPoolKeyStruct,
    value1: BigInt,
  ) {
    this.value0 = value0;
    this.value1 = value1;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromTuple(this.value0));
    map.set("value1", ethereum.Value.fromUnsignedBigInt(this.value1));
    return map;
  }

  getPoolKey(): PositionManager__getPoolAndPositionInfoResultPoolKeyStruct {
    return this.value0;
  }

  getInfo(): BigInt {
    return this.value1;
  }
}

export class PositionManager__poolKeysResult {
  value0: Address;
  value1: Address;
  value2: Address;
  value3: Address;
  value4: i32;
  value5: Bytes;

  constructor(
    value0: Address,
    value1: Address,
    value2: Address,
    value3: Address,
    value4: i32,
    value5: Bytes,
  ) {
    this.value0 = value0;
    this.value1 = value1;
    this.value2 = value2;
    this.value3 = value3;
    this.value4 = value4;
    this.value5 = value5;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromAddress(this.value0));
    map.set("value1", ethereum.Value.fromAddress(this.value1));
    map.set("value2", ethereum.Value.fromAddress(this.value2));
    map.set("value3", ethereum.Value.fromAddress(this.value3));
    map.set(
      "value4",
      ethereum.Value.fromUnsignedBigInt(BigInt.fromI32(this.value4)),
    );
    map.set("value5", ethereum.Value.fromFixedBytes(this.value5));
    return map;
  }

  getCurrency0(): Address {
    return this.value0;
  }

  getCurrency1(): Address {
    return this.value1;
  }

  getHooks(): Address {
    return this.value2;
  }

  getPoolManager(): Address {
    return this.value3;
  }

  getFee(): i32 {
    return this.value4;
  }

  getParameters(): Bytes {
    return this.value5;
  }
}

export class PositionManager__positionsResultPoolKeyStruct extends ethereum.Tuple {
  get currency0(): Address {
    return this[0].toAddress();
  }

  get currency1(): Address {
    return this[1].toAddress();
  }

  get hooks(): Address {
    return this[2].toAddress();
  }

  get poolManager(): Address {
    return this[3].toAddress();
  }

  get fee(): i32 {
    return this[4].toI32();
  }

  get parameters(): Bytes {
    return this[5].toBytes();
  }
}

export class PositionManager__positionsResult {
  value0: PositionManager__positionsResultPoolKeyStruct;
  value1: i32;
  value2: i32;
  value3: BigInt;
  value4: BigInt;
  value5: BigInt;
  value6: Address;

  constructor(
    value0: PositionManager__positionsResultPoolKeyStruct,
    value1: i32,
    value2: i32,
    value3: BigInt,
    value4: BigInt,
    value5: BigInt,
    value6: Address,
  ) {
    this.value0 = value0;
    this.value1 = value1;
    this.value2 = value2;
    this.value3 = value3;
    this.value4 = value4;
    this.value5 = value5;
    this.value6 = value6;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromTuple(this.value0));
    map.set("value1", ethereum.Value.fromI32(this.value1));
    map.set("value2", ethereum.Value.fromI32(this.value2));
    map.set("value3", ethereum.Value.fromUnsignedBigInt(this.value3));
    map.set("value4", ethereum.Value.fromUnsignedBigInt(this.value4));
    map.set("value5", ethereum.Value.fromUnsignedBigInt(this.value5));
    map.set("value6", ethereum.Value.fromAddress(this.value6));
    return map;
  }

  getPoolKey(): PositionManager__positionsResultPoolKeyStruct {
    return this.value0;
  }

  getTickLower(): i32 {
    return this.value1;
  }

  getTickUpper(): i32 {
    return this.value2;
  }

  getLiquidity(): BigInt {
    return this.value3;
  }

  getFeeGrowthInside0LastX128(): BigInt {
    return this.value4;
  }

  getFeeGrowthInside1LastX128(): BigInt {
    return this.value5;
  }

  get_subscriber(): Address {
    return this.value6;
  }
}

export class PositionManager extends ethereum.SmartContract {
  static bind(address: Address): PositionManager {
    return new PositionManager("PositionManager", address);
  }

  DOMAIN_SEPARATOR(): Bytes {
    let result = super.call(
      "DOMAIN_SEPARATOR",
      "DOMAIN_SEPARATOR():(bytes32)",
      [],
    );

    return result[0].toBytes();
  }

  try_DOMAIN_SEPARATOR(): ethereum.CallResult<Bytes> {
    let result = super.tryCall(
      "DOMAIN_SEPARATOR",
      "DOMAIN_SEPARATOR():(bytes32)",
      [],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBytes());
  }

  WETH9(): Address {
    let result = super.call("WETH9", "WETH9():(address)", []);

    return result[0].toAddress();
  }

  try_WETH9(): ethereum.CallResult<Address> {
    let result = super.tryCall("WETH9", "WETH9():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  balanceOf(owner: Address): BigInt {
    let result = super.call("balanceOf", "balanceOf(address):(uint256)", [
      ethereum.Value.fromAddress(owner),
    ]);

    return result[0].toBigInt();
  }

  try_balanceOf(owner: Address): ethereum.CallResult<BigInt> {
    let result = super.tryCall("balanceOf", "balanceOf(address):(uint256)", [
      ethereum.Value.fromAddress(owner),
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  clPoolManager(): Address {
    let result = super.call("clPoolManager", "clPoolManager():(address)", []);

    return result[0].toAddress();
  }

  try_clPoolManager(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "clPoolManager",
      "clPoolManager():(address)",
      [],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  getApproved(param0: BigInt): Address {
    let result = super.call("getApproved", "getApproved(uint256):(address)", [
      ethereum.Value.fromUnsignedBigInt(param0),
    ]);

    return result[0].toAddress();
  }

  try_getApproved(param0: BigInt): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "getApproved",
      "getApproved(uint256):(address)",
      [ethereum.Value.fromUnsignedBigInt(param0)],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  getPoolAndPositionInfo(
    tokenId: BigInt,
  ): PositionManager__getPoolAndPositionInfoResult {
    let result = super.call(
      "getPoolAndPositionInfo",
      "getPoolAndPositionInfo(uint256):((address,address,address,address,uint24,bytes32),uint256)",
      [ethereum.Value.fromUnsignedBigInt(tokenId)],
    );

    return changetype<PositionManager__getPoolAndPositionInfoResult>(
      new PositionManager__getPoolAndPositionInfoResult(
        changetype<PositionManager__getPoolAndPositionInfoResultPoolKeyStruct>(
          result[0].toTuple(),
        ),
        result[1].toBigInt(),
      ),
    );
  }

  try_getPoolAndPositionInfo(
    tokenId: BigInt,
  ): ethereum.CallResult<PositionManager__getPoolAndPositionInfoResult> {
    let result = super.tryCall(
      "getPoolAndPositionInfo",
      "getPoolAndPositionInfo(uint256):((address,address,address,address,uint24,bytes32),uint256)",
      [ethereum.Value.fromUnsignedBigInt(tokenId)],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      changetype<PositionManager__getPoolAndPositionInfoResult>(
        new PositionManager__getPoolAndPositionInfoResult(
          changetype<PositionManager__getPoolAndPositionInfoResultPoolKeyStruct>(
            value[0].toTuple(),
          ),
          value[1].toBigInt(),
        ),
      ),
    );
  }

  getPositionLiquidity(tokenId: BigInt): BigInt {
    let result = super.call(
      "getPositionLiquidity",
      "getPositionLiquidity(uint256):(uint128)",
      [ethereum.Value.fromUnsignedBigInt(tokenId)],
    );

    return result[0].toBigInt();
  }

  try_getPositionLiquidity(tokenId: BigInt): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "getPositionLiquidity",
      "getPositionLiquidity(uint256):(uint128)",
      [ethereum.Value.fromUnsignedBigInt(tokenId)],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  isApprovedForAll(param0: Address, param1: Address): boolean {
    let result = super.call(
      "isApprovedForAll",
      "isApprovedForAll(address,address):(bool)",
      [ethereum.Value.fromAddress(param0), ethereum.Value.fromAddress(param1)],
    );

    return result[0].toBoolean();
  }

  try_isApprovedForAll(
    param0: Address,
    param1: Address,
  ): ethereum.CallResult<boolean> {
    let result = super.tryCall(
      "isApprovedForAll",
      "isApprovedForAll(address,address):(bool)",
      [ethereum.Value.fromAddress(param0), ethereum.Value.fromAddress(param1)],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBoolean());
  }

  lockAcquired(data: Bytes): Bytes {
    let result = super.call("lockAcquired", "lockAcquired(bytes):(bytes)", [
      ethereum.Value.fromBytes(data),
    ]);

    return result[0].toBytes();
  }

  try_lockAcquired(data: Bytes): ethereum.CallResult<Bytes> {
    let result = super.tryCall("lockAcquired", "lockAcquired(bytes):(bytes)", [
      ethereum.Value.fromBytes(data),
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBytes());
  }

  msgSender(): Address {
    let result = super.call("msgSender", "msgSender():(address)", []);

    return result[0].toAddress();
  }

  try_msgSender(): ethereum.CallResult<Address> {
    let result = super.tryCall("msgSender", "msgSender():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  name(): string {
    let result = super.call("name", "name():(string)", []);

    return result[0].toString();
  }

  try_name(): ethereum.CallResult<string> {
    let result = super.tryCall("name", "name():(string)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toString());
  }

  nextTokenId(): BigInt {
    let result = super.call("nextTokenId", "nextTokenId():(uint256)", []);

    return result[0].toBigInt();
  }

  try_nextTokenId(): ethereum.CallResult<BigInt> {
    let result = super.tryCall("nextTokenId", "nextTokenId():(uint256)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  nonces(owner: Address, word: BigInt): BigInt {
    let result = super.call("nonces", "nonces(address,uint256):(uint256)", [
      ethereum.Value.fromAddress(owner),
      ethereum.Value.fromUnsignedBigInt(word),
    ]);

    return result[0].toBigInt();
  }

  try_nonces(owner: Address, word: BigInt): ethereum.CallResult<BigInt> {
    let result = super.tryCall("nonces", "nonces(address,uint256):(uint256)", [
      ethereum.Value.fromAddress(owner),
      ethereum.Value.fromUnsignedBigInt(word),
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  ownerOf(id: BigInt): Address {
    let result = super.call("ownerOf", "ownerOf(uint256):(address)", [
      ethereum.Value.fromUnsignedBigInt(id),
    ]);

    return result[0].toAddress();
  }

  try_ownerOf(id: BigInt): ethereum.CallResult<Address> {
    let result = super.tryCall("ownerOf", "ownerOf(uint256):(address)", [
      ethereum.Value.fromUnsignedBigInt(id),
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  permit2(): Address {
    let result = super.call("permit2", "permit2():(address)", []);

    return result[0].toAddress();
  }

  try_permit2(): ethereum.CallResult<Address> {
    let result = super.tryCall("permit2", "permit2():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  poolKeys(poolId: Bytes): PositionManager__poolKeysResult {
    let result = super.call(
      "poolKeys",
      "poolKeys(bytes25):(address,address,address,address,uint24,bytes32)",
      [ethereum.Value.fromFixedBytes(poolId)],
    );

    return new PositionManager__poolKeysResult(
      result[0].toAddress(),
      result[1].toAddress(),
      result[2].toAddress(),
      result[3].toAddress(),
      result[4].toI32(),
      result[5].toBytes(),
    );
  }

  try_poolKeys(
    poolId: Bytes,
  ): ethereum.CallResult<PositionManager__poolKeysResult> {
    let result = super.tryCall(
      "poolKeys",
      "poolKeys(bytes25):(address,address,address,address,uint24,bytes32)",
      [ethereum.Value.fromFixedBytes(poolId)],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      new PositionManager__poolKeysResult(
        value[0].toAddress(),
        value[1].toAddress(),
        value[2].toAddress(),
        value[3].toAddress(),
        value[4].toI32(),
        value[5].toBytes(),
      ),
    );
  }

  positionInfo(tokenId: BigInt): BigInt {
    let result = super.call("positionInfo", "positionInfo(uint256):(uint256)", [
      ethereum.Value.fromUnsignedBigInt(tokenId),
    ]);

    return result[0].toBigInt();
  }

  try_positionInfo(tokenId: BigInt): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "positionInfo",
      "positionInfo(uint256):(uint256)",
      [ethereum.Value.fromUnsignedBigInt(tokenId)],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  positions(tokenId: BigInt): PositionManager__positionsResult {
    let result = super.call(
      "positions",
      "positions(uint256):((address,address,address,address,uint24,bytes32),int24,int24,uint128,uint256,uint256,address)",
      [ethereum.Value.fromUnsignedBigInt(tokenId)],
    );

    return changetype<PositionManager__positionsResult>(
      new PositionManager__positionsResult(
        changetype<PositionManager__positionsResultPoolKeyStruct>(
          result[0].toTuple(),
        ),
        result[1].toI32(),
        result[2].toI32(),
        result[3].toBigInt(),
        result[4].toBigInt(),
        result[5].toBigInt(),
        result[6].toAddress(),
      ),
    );
  }

  try_positions(
    tokenId: BigInt,
  ): ethereum.CallResult<PositionManager__positionsResult> {
    let result = super.tryCall(
      "positions",
      "positions(uint256):((address,address,address,address,uint24,bytes32),int24,int24,uint128,uint256,uint256,address)",
      [ethereum.Value.fromUnsignedBigInt(tokenId)],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      changetype<PositionManager__positionsResult>(
        new PositionManager__positionsResult(
          changetype<PositionManager__positionsResultPoolKeyStruct>(
            value[0].toTuple(),
          ),
          value[1].toI32(),
          value[2].toI32(),
          value[3].toBigInt(),
          value[4].toBigInt(),
          value[5].toBigInt(),
          value[6].toAddress(),
        ),
      ),
    );
  }

  subscriber(tokenId: BigInt): Address {
    let result = super.call("subscriber", "subscriber(uint256):(address)", [
      ethereum.Value.fromUnsignedBigInt(tokenId),
    ]);

    return result[0].toAddress();
  }

  try_subscriber(tokenId: BigInt): ethereum.CallResult<Address> {
    let result = super.tryCall("subscriber", "subscriber(uint256):(address)", [
      ethereum.Value.fromUnsignedBigInt(tokenId),
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  supportsInterface(interfaceId: Bytes): boolean {
    let result = super.call(
      "supportsInterface",
      "supportsInterface(bytes4):(bool)",
      [ethereum.Value.fromFixedBytes(interfaceId)],
    );

    return result[0].toBoolean();
  }

  try_supportsInterface(interfaceId: Bytes): ethereum.CallResult<boolean> {
    let result = super.tryCall(
      "supportsInterface",
      "supportsInterface(bytes4):(bool)",
      [ethereum.Value.fromFixedBytes(interfaceId)],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBoolean());
  }

  symbol(): string {
    let result = super.call("symbol", "symbol():(string)", []);

    return result[0].toString();
  }

  try_symbol(): ethereum.CallResult<string> {
    let result = super.tryCall("symbol", "symbol():(string)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toString());
  }

  tokenDescriptor(): Address {
    let result = super.call(
      "tokenDescriptor",
      "tokenDescriptor():(address)",
      [],
    );

    return result[0].toAddress();
  }

  try_tokenDescriptor(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "tokenDescriptor",
      "tokenDescriptor():(address)",
      [],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  tokenURI(tokenId: BigInt): string {
    let result = super.call("tokenURI", "tokenURI(uint256):(string)", [
      ethereum.Value.fromUnsignedBigInt(tokenId),
    ]);

    return result[0].toString();
  }

  try_tokenURI(tokenId: BigInt): ethereum.CallResult<string> {
    let result = super.tryCall("tokenURI", "tokenURI(uint256):(string)", [
      ethereum.Value.fromUnsignedBigInt(tokenId),
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toString());
  }

  unsubscribeGasLimit(): BigInt {
    let result = super.call(
      "unsubscribeGasLimit",
      "unsubscribeGasLimit():(uint256)",
      [],
    );

    return result[0].toBigInt();
  }

  try_unsubscribeGasLimit(): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "unsubscribeGasLimit",
      "unsubscribeGasLimit():(uint256)",
      [],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  vault(): Address {
    let result = super.call("vault", "vault():(address)", []);

    return result[0].toAddress();
  }

  try_vault(): ethereum.CallResult<Address> {
    let result = super.tryCall("vault", "vault():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }
}

export class ConstructorCall extends ethereum.Call {
  get inputs(): ConstructorCall__Inputs {
    return new ConstructorCall__Inputs(this);
  }

  get outputs(): ConstructorCall__Outputs {
    return new ConstructorCall__Outputs(this);
  }
}

export class ConstructorCall__Inputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }

  get _vault(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get _clPoolManager(): Address {
    return this._call.inputValues[1].value.toAddress();
  }

  get _permit2(): Address {
    return this._call.inputValues[2].value.toAddress();
  }

  get _unsubscribeGasLimit(): BigInt {
    return this._call.inputValues[3].value.toBigInt();
  }

  get _tokenDescriptor(): Address {
    return this._call.inputValues[4].value.toAddress();
  }

  get _weth9(): Address {
    return this._call.inputValues[5].value.toAddress();
  }
}

export class ConstructorCall__Outputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }
}

export class ApproveCall extends ethereum.Call {
  get inputs(): ApproveCall__Inputs {
    return new ApproveCall__Inputs(this);
  }

  get outputs(): ApproveCall__Outputs {
    return new ApproveCall__Outputs(this);
  }
}

export class ApproveCall__Inputs {
  _call: ApproveCall;

  constructor(call: ApproveCall) {
    this._call = call;
  }

  get spender(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get id(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }
}

export class ApproveCall__Outputs {
  _call: ApproveCall;

  constructor(call: ApproveCall) {
    this._call = call;
  }
}

export class InitializePoolCall extends ethereum.Call {
  get inputs(): InitializePoolCall__Inputs {
    return new InitializePoolCall__Inputs(this);
  }

  get outputs(): InitializePoolCall__Outputs {
    return new InitializePoolCall__Outputs(this);
  }
}

export class InitializePoolCall__Inputs {
  _call: InitializePoolCall;

  constructor(call: InitializePoolCall) {
    this._call = call;
  }

  get key(): InitializePoolCallKeyStruct {
    return changetype<InitializePoolCallKeyStruct>(
      this._call.inputValues[0].value.toTuple(),
    );
  }

  get sqrtPriceX96(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }
}

export class InitializePoolCall__Outputs {
  _call: InitializePoolCall;

  constructor(call: InitializePoolCall) {
    this._call = call;
  }

  get value0(): i32 {
    return this._call.outputValues[0].value.toI32();
  }
}

export class InitializePoolCallKeyStruct extends ethereum.Tuple {
  get currency0(): Address {
    return this[0].toAddress();
  }

  get currency1(): Address {
    return this[1].toAddress();
  }

  get hooks(): Address {
    return this[2].toAddress();
  }

  get poolManager(): Address {
    return this[3].toAddress();
  }

  get fee(): i32 {
    return this[4].toI32();
  }

  get parameters(): Bytes {
    return this[5].toBytes();
  }
}

export class LockAcquiredCall extends ethereum.Call {
  get inputs(): LockAcquiredCall__Inputs {
    return new LockAcquiredCall__Inputs(this);
  }

  get outputs(): LockAcquiredCall__Outputs {
    return new LockAcquiredCall__Outputs(this);
  }
}

export class LockAcquiredCall__Inputs {
  _call: LockAcquiredCall;

  constructor(call: LockAcquiredCall) {
    this._call = call;
  }

  get data(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }
}

export class LockAcquiredCall__Outputs {
  _call: LockAcquiredCall;

  constructor(call: LockAcquiredCall) {
    this._call = call;
  }

  get value0(): Bytes {
    return this._call.outputValues[0].value.toBytes();
  }
}

export class ModifyLiquiditiesCall extends ethereum.Call {
  get inputs(): ModifyLiquiditiesCall__Inputs {
    return new ModifyLiquiditiesCall__Inputs(this);
  }

  get outputs(): ModifyLiquiditiesCall__Outputs {
    return new ModifyLiquiditiesCall__Outputs(this);
  }
}

export class ModifyLiquiditiesCall__Inputs {
  _call: ModifyLiquiditiesCall;

  constructor(call: ModifyLiquiditiesCall) {
    this._call = call;
  }

  get payload(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }

  get deadline(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }
}

export class ModifyLiquiditiesCall__Outputs {
  _call: ModifyLiquiditiesCall;

  constructor(call: ModifyLiquiditiesCall) {
    this._call = call;
  }
}

export class ModifyLiquiditiesWithoutLockCall extends ethereum.Call {
  get inputs(): ModifyLiquiditiesWithoutLockCall__Inputs {
    return new ModifyLiquiditiesWithoutLockCall__Inputs(this);
  }

  get outputs(): ModifyLiquiditiesWithoutLockCall__Outputs {
    return new ModifyLiquiditiesWithoutLockCall__Outputs(this);
  }
}

export class ModifyLiquiditiesWithoutLockCall__Inputs {
  _call: ModifyLiquiditiesWithoutLockCall;

  constructor(call: ModifyLiquiditiesWithoutLockCall) {
    this._call = call;
  }

  get actions(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }

  get params(): Array<Bytes> {
    return this._call.inputValues[1].value.toBytesArray();
  }
}

export class ModifyLiquiditiesWithoutLockCall__Outputs {
  _call: ModifyLiquiditiesWithoutLockCall;

  constructor(call: ModifyLiquiditiesWithoutLockCall) {
    this._call = call;
  }
}

export class MulticallCall extends ethereum.Call {
  get inputs(): MulticallCall__Inputs {
    return new MulticallCall__Inputs(this);
  }

  get outputs(): MulticallCall__Outputs {
    return new MulticallCall__Outputs(this);
  }
}

export class MulticallCall__Inputs {
  _call: MulticallCall;

  constructor(call: MulticallCall) {
    this._call = call;
  }

  get data(): Array<Bytes> {
    return this._call.inputValues[0].value.toBytesArray();
  }
}

export class MulticallCall__Outputs {
  _call: MulticallCall;

  constructor(call: MulticallCall) {
    this._call = call;
  }

  get results(): Array<Bytes> {
    return this._call.outputValues[0].value.toBytesArray();
  }
}

export class PermitCall extends ethereum.Call {
  get inputs(): PermitCall__Inputs {
    return new PermitCall__Inputs(this);
  }

  get outputs(): PermitCall__Outputs {
    return new PermitCall__Outputs(this);
  }
}

export class PermitCall__Inputs {
  _call: PermitCall;

  constructor(call: PermitCall) {
    this._call = call;
  }

  get spender(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get tokenId(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }

  get deadline(): BigInt {
    return this._call.inputValues[2].value.toBigInt();
  }

  get nonce(): BigInt {
    return this._call.inputValues[3].value.toBigInt();
  }

  get signature(): Bytes {
    return this._call.inputValues[4].value.toBytes();
  }
}

export class PermitCall__Outputs {
  _call: PermitCall;

  constructor(call: PermitCall) {
    this._call = call;
  }
}

export class Permit1Call extends ethereum.Call {
  get inputs(): Permit1Call__Inputs {
    return new Permit1Call__Inputs(this);
  }

  get outputs(): Permit1Call__Outputs {
    return new Permit1Call__Outputs(this);
  }
}

export class Permit1Call__Inputs {
  _call: Permit1Call;

  constructor(call: Permit1Call) {
    this._call = call;
  }

  get owner(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get permitSingle(): Permit1CallPermitSingleStruct {
    return changetype<Permit1CallPermitSingleStruct>(
      this._call.inputValues[1].value.toTuple(),
    );
  }

  get signature(): Bytes {
    return this._call.inputValues[2].value.toBytes();
  }
}

export class Permit1Call__Outputs {
  _call: Permit1Call;

  constructor(call: Permit1Call) {
    this._call = call;
  }

  get err(): Bytes {
    return this._call.outputValues[0].value.toBytes();
  }
}

export class Permit1CallPermitSingleStruct extends ethereum.Tuple {
  get details(): Permit1CallPermitSingleDetailsStruct {
    return changetype<Permit1CallPermitSingleDetailsStruct>(this[0].toTuple());
  }

  get spender(): Address {
    return this[1].toAddress();
  }

  get sigDeadline(): BigInt {
    return this[2].toBigInt();
  }
}

export class Permit1CallPermitSingleDetailsStruct extends ethereum.Tuple {
  get token(): Address {
    return this[0].toAddress();
  }

  get amount(): BigInt {
    return this[1].toBigInt();
  }

  get expiration(): BigInt {
    return this[2].toBigInt();
  }

  get nonce(): BigInt {
    return this[3].toBigInt();
  }
}

export class PermitBatchCall extends ethereum.Call {
  get inputs(): PermitBatchCall__Inputs {
    return new PermitBatchCall__Inputs(this);
  }

  get outputs(): PermitBatchCall__Outputs {
    return new PermitBatchCall__Outputs(this);
  }
}

export class PermitBatchCall__Inputs {
  _call: PermitBatchCall;

  constructor(call: PermitBatchCall) {
    this._call = call;
  }

  get owner(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get _permitBatch(): PermitBatchCall_permitBatchStruct {
    return changetype<PermitBatchCall_permitBatchStruct>(
      this._call.inputValues[1].value.toTuple(),
    );
  }

  get signature(): Bytes {
    return this._call.inputValues[2].value.toBytes();
  }
}

export class PermitBatchCall__Outputs {
  _call: PermitBatchCall;

  constructor(call: PermitBatchCall) {
    this._call = call;
  }

  get err(): Bytes {
    return this._call.outputValues[0].value.toBytes();
  }
}

export class PermitBatchCall_permitBatchStruct extends ethereum.Tuple {
  get details(): Array<PermitBatchCall_permitBatchDetailsStruct> {
    return this[0].toTupleArray<PermitBatchCall_permitBatchDetailsStruct>();
  }

  get spender(): Address {
    return this[1].toAddress();
  }

  get sigDeadline(): BigInt {
    return this[2].toBigInt();
  }
}

export class PermitBatchCall_permitBatchDetailsStruct extends ethereum.Tuple {
  get token(): Address {
    return this[0].toAddress();
  }

  get amount(): BigInt {
    return this[1].toBigInt();
  }

  get expiration(): BigInt {
    return this[2].toBigInt();
  }

  get nonce(): BigInt {
    return this[3].toBigInt();
  }
}

export class PermitForAllCall extends ethereum.Call {
  get inputs(): PermitForAllCall__Inputs {
    return new PermitForAllCall__Inputs(this);
  }

  get outputs(): PermitForAllCall__Outputs {
    return new PermitForAllCall__Outputs(this);
  }
}

export class PermitForAllCall__Inputs {
  _call: PermitForAllCall;

  constructor(call: PermitForAllCall) {
    this._call = call;
  }

  get owner(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get operator(): Address {
    return this._call.inputValues[1].value.toAddress();
  }

  get approved(): boolean {
    return this._call.inputValues[2].value.toBoolean();
  }

  get deadline(): BigInt {
    return this._call.inputValues[3].value.toBigInt();
  }

  get nonce(): BigInt {
    return this._call.inputValues[4].value.toBigInt();
  }

  get signature(): Bytes {
    return this._call.inputValues[5].value.toBytes();
  }
}

export class PermitForAllCall__Outputs {
  _call: PermitForAllCall;

  constructor(call: PermitForAllCall) {
    this._call = call;
  }
}

export class RevokeNonceCall extends ethereum.Call {
  get inputs(): RevokeNonceCall__Inputs {
    return new RevokeNonceCall__Inputs(this);
  }

  get outputs(): RevokeNonceCall__Outputs {
    return new RevokeNonceCall__Outputs(this);
  }
}

export class RevokeNonceCall__Inputs {
  _call: RevokeNonceCall;

  constructor(call: RevokeNonceCall) {
    this._call = call;
  }

  get nonce(): BigInt {
    return this._call.inputValues[0].value.toBigInt();
  }
}

export class RevokeNonceCall__Outputs {
  _call: RevokeNonceCall;

  constructor(call: RevokeNonceCall) {
    this._call = call;
  }
}

export class SafeTransferFromCall extends ethereum.Call {
  get inputs(): SafeTransferFromCall__Inputs {
    return new SafeTransferFromCall__Inputs(this);
  }

  get outputs(): SafeTransferFromCall__Outputs {
    return new SafeTransferFromCall__Outputs(this);
  }
}

export class SafeTransferFromCall__Inputs {
  _call: SafeTransferFromCall;

  constructor(call: SafeTransferFromCall) {
    this._call = call;
  }

  get from(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get to(): Address {
    return this._call.inputValues[1].value.toAddress();
  }

  get id(): BigInt {
    return this._call.inputValues[2].value.toBigInt();
  }
}

export class SafeTransferFromCall__Outputs {
  _call: SafeTransferFromCall;

  constructor(call: SafeTransferFromCall) {
    this._call = call;
  }
}

export class SafeTransferFrom1Call extends ethereum.Call {
  get inputs(): SafeTransferFrom1Call__Inputs {
    return new SafeTransferFrom1Call__Inputs(this);
  }

  get outputs(): SafeTransferFrom1Call__Outputs {
    return new SafeTransferFrom1Call__Outputs(this);
  }
}

export class SafeTransferFrom1Call__Inputs {
  _call: SafeTransferFrom1Call;

  constructor(call: SafeTransferFrom1Call) {
    this._call = call;
  }

  get from(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get to(): Address {
    return this._call.inputValues[1].value.toAddress();
  }

  get id(): BigInt {
    return this._call.inputValues[2].value.toBigInt();
  }

  get data(): Bytes {
    return this._call.inputValues[3].value.toBytes();
  }
}

export class SafeTransferFrom1Call__Outputs {
  _call: SafeTransferFrom1Call;

  constructor(call: SafeTransferFrom1Call) {
    this._call = call;
  }
}

export class SetApprovalForAllCall extends ethereum.Call {
  get inputs(): SetApprovalForAllCall__Inputs {
    return new SetApprovalForAllCall__Inputs(this);
  }

  get outputs(): SetApprovalForAllCall__Outputs {
    return new SetApprovalForAllCall__Outputs(this);
  }
}

export class SetApprovalForAllCall__Inputs {
  _call: SetApprovalForAllCall;

  constructor(call: SetApprovalForAllCall) {
    this._call = call;
  }

  get operator(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get approved(): boolean {
    return this._call.inputValues[1].value.toBoolean();
  }
}

export class SetApprovalForAllCall__Outputs {
  _call: SetApprovalForAllCall;

  constructor(call: SetApprovalForAllCall) {
    this._call = call;
  }
}

export class SubscribeCall extends ethereum.Call {
  get inputs(): SubscribeCall__Inputs {
    return new SubscribeCall__Inputs(this);
  }

  get outputs(): SubscribeCall__Outputs {
    return new SubscribeCall__Outputs(this);
  }
}

export class SubscribeCall__Inputs {
  _call: SubscribeCall;

  constructor(call: SubscribeCall) {
    this._call = call;
  }

  get tokenId(): BigInt {
    return this._call.inputValues[0].value.toBigInt();
  }

  get newSubscriber(): Address {
    return this._call.inputValues[1].value.toAddress();
  }

  get data(): Bytes {
    return this._call.inputValues[2].value.toBytes();
  }
}

export class SubscribeCall__Outputs {
  _call: SubscribeCall;

  constructor(call: SubscribeCall) {
    this._call = call;
  }
}

export class TransferFromCall extends ethereum.Call {
  get inputs(): TransferFromCall__Inputs {
    return new TransferFromCall__Inputs(this);
  }

  get outputs(): TransferFromCall__Outputs {
    return new TransferFromCall__Outputs(this);
  }
}

export class TransferFromCall__Inputs {
  _call: TransferFromCall;

  constructor(call: TransferFromCall) {
    this._call = call;
  }

  get from(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get to(): Address {
    return this._call.inputValues[1].value.toAddress();
  }

  get id(): BigInt {
    return this._call.inputValues[2].value.toBigInt();
  }
}

export class TransferFromCall__Outputs {
  _call: TransferFromCall;

  constructor(call: TransferFromCall) {
    this._call = call;
  }
}

export class UnsubscribeCall extends ethereum.Call {
  get inputs(): UnsubscribeCall__Inputs {
    return new UnsubscribeCall__Inputs(this);
  }

  get outputs(): UnsubscribeCall__Outputs {
    return new UnsubscribeCall__Outputs(this);
  }
}

export class UnsubscribeCall__Inputs {
  _call: UnsubscribeCall;

  constructor(call: UnsubscribeCall) {
    this._call = call;
  }

  get tokenId(): BigInt {
    return this._call.inputValues[0].value.toBigInt();
  }
}

export class UnsubscribeCall__Outputs {
  _call: UnsubscribeCall;

  constructor(call: UnsubscribeCall) {
    this._call = call;
  }
}
