// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  ethereum,
  JSONValue,
  TypedMap,
  Entity,
  Bytes,
  Address,
  BigInt,
} from "@graphprotocol/graph-ts";

export class Donate extends ethereum.Event {
  get params(): Donate__Params {
    return new Donate__Params(this);
  }
}

export class Donate__Params {
  _event: Donate;

  constructor(event: Donate) {
    this._event = event;
  }

  get id(): Bytes {
    return this._event.parameters[0].value.toBytes();
  }

  get sender(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get amount0(): BigInt {
    return this._event.parameters[2].value.toBigInt();
  }

  get amount1(): BigInt {
    return this._event.parameters[3].value.toBigInt();
  }

  get tick(): i32 {
    return this._event.parameters[4].value.toI32();
  }
}

export class DynamicLPFeeUpdated extends ethereum.Event {
  get params(): DynamicLPFeeUpdated__Params {
    return new DynamicLPFeeUpdated__Params(this);
  }
}

export class DynamicLPFeeUpdated__Params {
  _event: DynamicLPFeeUpdated;

  constructor(event: DynamicLPFeeUpdated) {
    this._event = event;
  }

  get id(): Bytes {
    return this._event.parameters[0].value.toBytes();
  }

  get dynamicLPFee(): i32 {
    return this._event.parameters[1].value.toI32();
  }
}

export class Initialize extends ethereum.Event {
  get params(): Initialize__Params {
    return new Initialize__Params(this);
  }
}

export class Initialize__Params {
  _event: Initialize;

  constructor(event: Initialize) {
    this._event = event;
  }

  get id(): Bytes {
    return this._event.parameters[0].value.toBytes();
  }

  get currency0(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get currency1(): Address {
    return this._event.parameters[2].value.toAddress();
  }

  get hooks(): Address {
    return this._event.parameters[3].value.toAddress();
  }

  get fee(): i32 {
    return this._event.parameters[4].value.toI32();
  }

  get parameters(): Bytes {
    return this._event.parameters[5].value.toBytes();
  }

  get sqrtPriceX96(): BigInt {
    return this._event.parameters[6].value.toBigInt();
  }

  get tick(): i32 {
    return this._event.parameters[7].value.toI32();
  }
}

export class ModifyLiquidity extends ethereum.Event {
  get params(): ModifyLiquidity__Params {
    return new ModifyLiquidity__Params(this);
  }
}

export class ModifyLiquidity__Params {
  _event: ModifyLiquidity;

  constructor(event: ModifyLiquidity) {
    this._event = event;
  }

  get id(): Bytes {
    return this._event.parameters[0].value.toBytes();
  }

  get sender(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get tickLower(): i32 {
    return this._event.parameters[2].value.toI32();
  }

  get tickUpper(): i32 {
    return this._event.parameters[3].value.toI32();
  }

  get liquidityDelta(): BigInt {
    return this._event.parameters[4].value.toBigInt();
  }

  get salt(): Bytes {
    return this._event.parameters[5].value.toBytes();
  }
}

export class OwnershipTransferred extends ethereum.Event {
  get params(): OwnershipTransferred__Params {
    return new OwnershipTransferred__Params(this);
  }
}

export class OwnershipTransferred__Params {
  _event: OwnershipTransferred;

  constructor(event: OwnershipTransferred) {
    this._event = event;
  }

  get previousOwner(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get newOwner(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class Paused extends ethereum.Event {
  get params(): Paused__Params {
    return new Paused__Params(this);
  }
}

export class Paused__Params {
  _event: Paused;

  constructor(event: Paused) {
    this._event = event;
  }

  get account(): Address {
    return this._event.parameters[0].value.toAddress();
  }
}

export class ProtocolFeeControllerUpdated extends ethereum.Event {
  get params(): ProtocolFeeControllerUpdated__Params {
    return new ProtocolFeeControllerUpdated__Params(this);
  }
}

export class ProtocolFeeControllerUpdated__Params {
  _event: ProtocolFeeControllerUpdated;

  constructor(event: ProtocolFeeControllerUpdated) {
    this._event = event;
  }

  get protocolFeeController(): Address {
    return this._event.parameters[0].value.toAddress();
  }
}

export class ProtocolFeeUpdated extends ethereum.Event {
  get params(): ProtocolFeeUpdated__Params {
    return new ProtocolFeeUpdated__Params(this);
  }
}

export class ProtocolFeeUpdated__Params {
  _event: ProtocolFeeUpdated;

  constructor(event: ProtocolFeeUpdated) {
    this._event = event;
  }

  get id(): Bytes {
    return this._event.parameters[0].value.toBytes();
  }

  get protocolFee(): i32 {
    return this._event.parameters[1].value.toI32();
  }
}

export class Swap extends ethereum.Event {
  get params(): Swap__Params {
    return new Swap__Params(this);
  }
}

export class Swap__Params {
  _event: Swap;

  constructor(event: Swap) {
    this._event = event;
  }

  get id(): Bytes {
    return this._event.parameters[0].value.toBytes();
  }

  get sender(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get amount0(): BigInt {
    return this._event.parameters[2].value.toBigInt();
  }

  get amount1(): BigInt {
    return this._event.parameters[3].value.toBigInt();
  }

  get sqrtPriceX96(): BigInt {
    return this._event.parameters[4].value.toBigInt();
  }

  get liquidity(): BigInt {
    return this._event.parameters[5].value.toBigInt();
  }

  get tick(): i32 {
    return this._event.parameters[6].value.toI32();
  }

  get fee(): i32 {
    return this._event.parameters[7].value.toI32();
  }

  get protocolFee(): i32 {
    return this._event.parameters[8].value.toI32();
  }
}

export class Unpaused extends ethereum.Event {
  get params(): Unpaused__Params {
    return new Unpaused__Params(this);
  }
}

export class Unpaused__Params {
  _event: Unpaused;

  constructor(event: Unpaused) {
    this._event = event;
  }

  get account(): Address {
    return this._event.parameters[0].value.toAddress();
  }
}

export class PoolManager__donateInputKeyStruct extends ethereum.Tuple {
  get currency0(): Address {
    return this[0].toAddress();
  }

  get currency1(): Address {
    return this[1].toAddress();
  }

  get hooks(): Address {
    return this[2].toAddress();
  }

  get poolManager(): Address {
    return this[3].toAddress();
  }

  get fee(): i32 {
    return this[4].toI32();
  }

  get parameters(): Bytes {
    return this[5].toBytes();
  }
}

export class PoolManager__getFeeGrowthGlobalsResult {
  value0: BigInt;
  value1: BigInt;

  constructor(value0: BigInt, value1: BigInt) {
    this.value0 = value0;
    this.value1 = value1;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromUnsignedBigInt(this.value0));
    map.set("value1", ethereum.Value.fromUnsignedBigInt(this.value1));
    return map;
  }

  getFeeGrowthGlobal0x128(): BigInt {
    return this.value0;
  }

  getFeeGrowthGlobal1x128(): BigInt {
    return this.value1;
  }
}

export class PoolManager__getPoolTickInfoResultValue0Struct extends ethereum.Tuple {
  get liquidityGross(): BigInt {
    return this[0].toBigInt();
  }

  get liquidityNet(): BigInt {
    return this[1].toBigInt();
  }

  get feeGrowthOutside0X128(): BigInt {
    return this[2].toBigInt();
  }

  get feeGrowthOutside1X128(): BigInt {
    return this[3].toBigInt();
  }
}

export class PoolManager__getPositionResultPositionStruct extends ethereum.Tuple {
  get liquidity(): BigInt {
    return this[0].toBigInt();
  }

  get feeGrowthInside0LastX128(): BigInt {
    return this[1].toBigInt();
  }

  get feeGrowthInside1LastX128(): BigInt {
    return this[2].toBigInt();
  }
}

export class PoolManager__getSlot0Result {
  value0: BigInt;
  value1: i32;
  value2: i32;
  value3: i32;

  constructor(value0: BigInt, value1: i32, value2: i32, value3: i32) {
    this.value0 = value0;
    this.value1 = value1;
    this.value2 = value2;
    this.value3 = value3;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromUnsignedBigInt(this.value0));
    map.set("value1", ethereum.Value.fromI32(this.value1));
    map.set(
      "value2",
      ethereum.Value.fromUnsignedBigInt(BigInt.fromI32(this.value2)),
    );
    map.set(
      "value3",
      ethereum.Value.fromUnsignedBigInt(BigInt.fromI32(this.value3)),
    );
    return map;
  }

  getSqrtPriceX96(): BigInt {
    return this.value0;
  }

  getTick(): i32 {
    return this.value1;
  }

  getProtocolFee(): i32 {
    return this.value2;
  }

  getLpFee(): i32 {
    return this.value3;
  }
}

export class PoolManager__initializeInputKeyStruct extends ethereum.Tuple {
  get currency0(): Address {
    return this[0].toAddress();
  }

  get currency1(): Address {
    return this[1].toAddress();
  }

  get hooks(): Address {
    return this[2].toAddress();
  }

  get poolManager(): Address {
    return this[3].toAddress();
  }

  get fee(): i32 {
    return this[4].toI32();
  }

  get parameters(): Bytes {
    return this[5].toBytes();
  }
}

export class PoolManager__modifyLiquidityResult {
  value0: BigInt;
  value1: BigInt;

  constructor(value0: BigInt, value1: BigInt) {
    this.value0 = value0;
    this.value1 = value1;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromSignedBigInt(this.value0));
    map.set("value1", ethereum.Value.fromSignedBigInt(this.value1));
    return map;
  }

  getDelta(): BigInt {
    return this.value0;
  }

  getFeeDelta(): BigInt {
    return this.value1;
  }
}

export class PoolManager__modifyLiquidityInputKeyStruct extends ethereum.Tuple {
  get currency0(): Address {
    return this[0].toAddress();
  }

  get currency1(): Address {
    return this[1].toAddress();
  }

  get hooks(): Address {
    return this[2].toAddress();
  }

  get poolManager(): Address {
    return this[3].toAddress();
  }

  get fee(): i32 {
    return this[4].toI32();
  }

  get parameters(): Bytes {
    return this[5].toBytes();
  }
}

export class PoolManager__modifyLiquidityInputParamsStruct extends ethereum.Tuple {
  get tickLower(): i32 {
    return this[0].toI32();
  }

  get tickUpper(): i32 {
    return this[1].toI32();
  }

  get liquidityDelta(): BigInt {
    return this[2].toBigInt();
  }

  get salt(): Bytes {
    return this[3].toBytes();
  }
}

export class PoolManager__poolIdToPoolKeyResult {
  value0: Address;
  value1: Address;
  value2: Address;
  value3: Address;
  value4: i32;
  value5: Bytes;

  constructor(
    value0: Address,
    value1: Address,
    value2: Address,
    value3: Address,
    value4: i32,
    value5: Bytes,
  ) {
    this.value0 = value0;
    this.value1 = value1;
    this.value2 = value2;
    this.value3 = value3;
    this.value4 = value4;
    this.value5 = value5;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromAddress(this.value0));
    map.set("value1", ethereum.Value.fromAddress(this.value1));
    map.set("value2", ethereum.Value.fromAddress(this.value2));
    map.set("value3", ethereum.Value.fromAddress(this.value3));
    map.set(
      "value4",
      ethereum.Value.fromUnsignedBigInt(BigInt.fromI32(this.value4)),
    );
    map.set("value5", ethereum.Value.fromFixedBytes(this.value5));
    return map;
  }

  getCurrency0(): Address {
    return this.value0;
  }

  getCurrency1(): Address {
    return this.value1;
  }

  getHooks(): Address {
    return this.value2;
  }

  getPoolManager(): Address {
    return this.value3;
  }

  getFee(): i32 {
    return this.value4;
  }

  getParameters(): Bytes {
    return this.value5;
  }
}

export class PoolManager__swapInputKeyStruct extends ethereum.Tuple {
  get currency0(): Address {
    return this[0].toAddress();
  }

  get currency1(): Address {
    return this[1].toAddress();
  }

  get hooks(): Address {
    return this[2].toAddress();
  }

  get poolManager(): Address {
    return this[3].toAddress();
  }

  get fee(): i32 {
    return this[4].toI32();
  }

  get parameters(): Bytes {
    return this[5].toBytes();
  }
}

export class PoolManager__swapInputParamsStruct extends ethereum.Tuple {
  get zeroForOne(): boolean {
    return this[0].toBoolean();
  }

  get amountSpecified(): BigInt {
    return this[1].toBigInt();
  }

  get sqrtPriceLimitX96(): BigInt {
    return this[2].toBigInt();
  }
}

export class PoolManager extends ethereum.SmartContract {
  static bind(address: Address): PoolManager {
    return new PoolManager("PoolManager", address);
  }

  collectProtocolFees(
    recipient: Address,
    currency: Address,
    amount: BigInt,
  ): BigInt {
    let result = super.call(
      "collectProtocolFees",
      "collectProtocolFees(address,address,uint256):(uint256)",
      [
        ethereum.Value.fromAddress(recipient),
        ethereum.Value.fromAddress(currency),
        ethereum.Value.fromUnsignedBigInt(amount),
      ],
    );

    return result[0].toBigInt();
  }

  try_collectProtocolFees(
    recipient: Address,
    currency: Address,
    amount: BigInt,
  ): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "collectProtocolFees",
      "collectProtocolFees(address,address,uint256):(uint256)",
      [
        ethereum.Value.fromAddress(recipient),
        ethereum.Value.fromAddress(currency),
        ethereum.Value.fromUnsignedBigInt(amount),
      ],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  donate(
    key: PoolManager__donateInputKeyStruct,
    amount0: BigInt,
    amount1: BigInt,
    hookData: Bytes,
  ): BigInt {
    let result = super.call(
      "donate",
      "donate((address,address,address,address,uint24,bytes32),uint256,uint256,bytes):(int256)",
      [
        ethereum.Value.fromTuple(key),
        ethereum.Value.fromUnsignedBigInt(amount0),
        ethereum.Value.fromUnsignedBigInt(amount1),
        ethereum.Value.fromBytes(hookData),
      ],
    );

    return result[0].toBigInt();
  }

  try_donate(
    key: PoolManager__donateInputKeyStruct,
    amount0: BigInt,
    amount1: BigInt,
    hookData: Bytes,
  ): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "donate",
      "donate((address,address,address,address,uint24,bytes32),uint256,uint256,bytes):(int256)",
      [
        ethereum.Value.fromTuple(key),
        ethereum.Value.fromUnsignedBigInt(amount0),
        ethereum.Value.fromUnsignedBigInt(amount1),
        ethereum.Value.fromBytes(hookData),
      ],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  extsload(slot: Bytes): Bytes {
    let result = super.call("extsload", "extsload(bytes32):(bytes32)", [
      ethereum.Value.fromFixedBytes(slot),
    ]);

    return result[0].toBytes();
  }

  try_extsload(slot: Bytes): ethereum.CallResult<Bytes> {
    let result = super.tryCall("extsload", "extsload(bytes32):(bytes32)", [
      ethereum.Value.fromFixedBytes(slot),
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBytes());
  }

  extsload1(slots: Array<Bytes>): Array<Bytes> {
    let result = super.call("extsload", "extsload(bytes32[]):(bytes32[])", [
      ethereum.Value.fromFixedBytesArray(slots),
    ]);

    return result[0].toBytesArray();
  }

  try_extsload1(slots: Array<Bytes>): ethereum.CallResult<Array<Bytes>> {
    let result = super.tryCall("extsload", "extsload(bytes32[]):(bytes32[])", [
      ethereum.Value.fromFixedBytesArray(slots),
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBytesArray());
  }

  getFeeGrowthGlobals(id: Bytes): PoolManager__getFeeGrowthGlobalsResult {
    let result = super.call(
      "getFeeGrowthGlobals",
      "getFeeGrowthGlobals(bytes32):(uint256,uint256)",
      [ethereum.Value.fromFixedBytes(id)],
    );

    return new PoolManager__getFeeGrowthGlobalsResult(
      result[0].toBigInt(),
      result[1].toBigInt(),
    );
  }

  try_getFeeGrowthGlobals(
    id: Bytes,
  ): ethereum.CallResult<PoolManager__getFeeGrowthGlobalsResult> {
    let result = super.tryCall(
      "getFeeGrowthGlobals",
      "getFeeGrowthGlobals(bytes32):(uint256,uint256)",
      [ethereum.Value.fromFixedBytes(id)],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      new PoolManager__getFeeGrowthGlobalsResult(
        value[0].toBigInt(),
        value[1].toBigInt(),
      ),
    );
  }

  getLiquidity(
    id: Bytes,
    _owner: Address,
    tickLower: i32,
    tickUpper: i32,
    salt: Bytes,
  ): BigInt {
    let result = super.call(
      "getLiquidity",
      "getLiquidity(bytes32,address,int24,int24,bytes32):(uint128)",
      [
        ethereum.Value.fromFixedBytes(id),
        ethereum.Value.fromAddress(_owner),
        ethereum.Value.fromI32(tickLower),
        ethereum.Value.fromI32(tickUpper),
        ethereum.Value.fromFixedBytes(salt),
      ],
    );

    return result[0].toBigInt();
  }

  try_getLiquidity(
    id: Bytes,
    _owner: Address,
    tickLower: i32,
    tickUpper: i32,
    salt: Bytes,
  ): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "getLiquidity",
      "getLiquidity(bytes32,address,int24,int24,bytes32):(uint128)",
      [
        ethereum.Value.fromFixedBytes(id),
        ethereum.Value.fromAddress(_owner),
        ethereum.Value.fromI32(tickLower),
        ethereum.Value.fromI32(tickUpper),
        ethereum.Value.fromFixedBytes(salt),
      ],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  getLiquidity1(id: Bytes): BigInt {
    let result = super.call("getLiquidity", "getLiquidity(bytes32):(uint128)", [
      ethereum.Value.fromFixedBytes(id),
    ]);

    return result[0].toBigInt();
  }

  try_getLiquidity1(id: Bytes): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "getLiquidity",
      "getLiquidity(bytes32):(uint128)",
      [ethereum.Value.fromFixedBytes(id)],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  getPoolBitmapInfo(id: Bytes, word: i32): BigInt {
    let result = super.call(
      "getPoolBitmapInfo",
      "getPoolBitmapInfo(bytes32,int16):(uint256)",
      [ethereum.Value.fromFixedBytes(id), ethereum.Value.fromI32(word)],
    );

    return result[0].toBigInt();
  }

  try_getPoolBitmapInfo(id: Bytes, word: i32): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "getPoolBitmapInfo",
      "getPoolBitmapInfo(bytes32,int16):(uint256)",
      [ethereum.Value.fromFixedBytes(id), ethereum.Value.fromI32(word)],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  getPoolTickInfo(
    id: Bytes,
    tick: i32,
  ): PoolManager__getPoolTickInfoResultValue0Struct {
    let result = super.call(
      "getPoolTickInfo",
      "getPoolTickInfo(bytes32,int24):((uint128,int128,uint256,uint256))",
      [ethereum.Value.fromFixedBytes(id), ethereum.Value.fromI32(tick)],
    );

    return changetype<PoolManager__getPoolTickInfoResultValue0Struct>(
      result[0].toTuple(),
    );
  }

  try_getPoolTickInfo(
    id: Bytes,
    tick: i32,
  ): ethereum.CallResult<PoolManager__getPoolTickInfoResultValue0Struct> {
    let result = super.tryCall(
      "getPoolTickInfo",
      "getPoolTickInfo(bytes32,int24):((uint128,int128,uint256,uint256))",
      [ethereum.Value.fromFixedBytes(id), ethereum.Value.fromI32(tick)],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      changetype<PoolManager__getPoolTickInfoResultValue0Struct>(
        value[0].toTuple(),
      ),
    );
  }

  getPosition(
    id: Bytes,
    owner: Address,
    tickLower: i32,
    tickUpper: i32,
    salt: Bytes,
  ): PoolManager__getPositionResultPositionStruct {
    let result = super.call(
      "getPosition",
      "getPosition(bytes32,address,int24,int24,bytes32):((uint128,uint256,uint256))",
      [
        ethereum.Value.fromFixedBytes(id),
        ethereum.Value.fromAddress(owner),
        ethereum.Value.fromI32(tickLower),
        ethereum.Value.fromI32(tickUpper),
        ethereum.Value.fromFixedBytes(salt),
      ],
    );

    return changetype<PoolManager__getPositionResultPositionStruct>(
      result[0].toTuple(),
    );
  }

  try_getPosition(
    id: Bytes,
    owner: Address,
    tickLower: i32,
    tickUpper: i32,
    salt: Bytes,
  ): ethereum.CallResult<PoolManager__getPositionResultPositionStruct> {
    let result = super.tryCall(
      "getPosition",
      "getPosition(bytes32,address,int24,int24,bytes32):((uint128,uint256,uint256))",
      [
        ethereum.Value.fromFixedBytes(id),
        ethereum.Value.fromAddress(owner),
        ethereum.Value.fromI32(tickLower),
        ethereum.Value.fromI32(tickUpper),
        ethereum.Value.fromFixedBytes(salt),
      ],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      changetype<PoolManager__getPositionResultPositionStruct>(
        value[0].toTuple(),
      ),
    );
  }

  getSlot0(id: Bytes): PoolManager__getSlot0Result {
    let result = super.call(
      "getSlot0",
      "getSlot0(bytes32):(uint160,int24,uint24,uint24)",
      [ethereum.Value.fromFixedBytes(id)],
    );

    return new PoolManager__getSlot0Result(
      result[0].toBigInt(),
      result[1].toI32(),
      result[2].toI32(),
      result[3].toI32(),
    );
  }

  try_getSlot0(id: Bytes): ethereum.CallResult<PoolManager__getSlot0Result> {
    let result = super.tryCall(
      "getSlot0",
      "getSlot0(bytes32):(uint160,int24,uint24,uint24)",
      [ethereum.Value.fromFixedBytes(id)],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      new PoolManager__getSlot0Result(
        value[0].toBigInt(),
        value[1].toI32(),
        value[2].toI32(),
        value[3].toI32(),
      ),
    );
  }

  initialize(
    key: PoolManager__initializeInputKeyStruct,
    sqrtPriceX96: BigInt,
  ): i32 {
    let result = super.call(
      "initialize",
      "initialize((address,address,address,address,uint24,bytes32),uint160):(int24)",
      [
        ethereum.Value.fromTuple(key),
        ethereum.Value.fromUnsignedBigInt(sqrtPriceX96),
      ],
    );

    return result[0].toI32();
  }

  try_initialize(
    key: PoolManager__initializeInputKeyStruct,
    sqrtPriceX96: BigInt,
  ): ethereum.CallResult<i32> {
    let result = super.tryCall(
      "initialize",
      "initialize((address,address,address,address,uint24,bytes32),uint160):(int24)",
      [
        ethereum.Value.fromTuple(key),
        ethereum.Value.fromUnsignedBigInt(sqrtPriceX96),
      ],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toI32());
  }

  modifyLiquidity(
    key: PoolManager__modifyLiquidityInputKeyStruct,
    params: PoolManager__modifyLiquidityInputParamsStruct,
    hookData: Bytes,
  ): PoolManager__modifyLiquidityResult {
    let result = super.call(
      "modifyLiquidity",
      "modifyLiquidity((address,address,address,address,uint24,bytes32),(int24,int24,int256,bytes32),bytes):(int256,int256)",
      [
        ethereum.Value.fromTuple(key),
        ethereum.Value.fromTuple(params),
        ethereum.Value.fromBytes(hookData),
      ],
    );

    return new PoolManager__modifyLiquidityResult(
      result[0].toBigInt(),
      result[1].toBigInt(),
    );
  }

  try_modifyLiquidity(
    key: PoolManager__modifyLiquidityInputKeyStruct,
    params: PoolManager__modifyLiquidityInputParamsStruct,
    hookData: Bytes,
  ): ethereum.CallResult<PoolManager__modifyLiquidityResult> {
    let result = super.tryCall(
      "modifyLiquidity",
      "modifyLiquidity((address,address,address,address,uint24,bytes32),(int24,int24,int256,bytes32),bytes):(int256,int256)",
      [
        ethereum.Value.fromTuple(key),
        ethereum.Value.fromTuple(params),
        ethereum.Value.fromBytes(hookData),
      ],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      new PoolManager__modifyLiquidityResult(
        value[0].toBigInt(),
        value[1].toBigInt(),
      ),
    );
  }

  owner(): Address {
    let result = super.call("owner", "owner():(address)", []);

    return result[0].toAddress();
  }

  try_owner(): ethereum.CallResult<Address> {
    let result = super.tryCall("owner", "owner():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  paused(): boolean {
    let result = super.call("paused", "paused():(bool)", []);

    return result[0].toBoolean();
  }

  try_paused(): ethereum.CallResult<boolean> {
    let result = super.tryCall("paused", "paused():(bool)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBoolean());
  }

  poolIdToPoolKey(id: Bytes): PoolManager__poolIdToPoolKeyResult {
    let result = super.call(
      "poolIdToPoolKey",
      "poolIdToPoolKey(bytes32):(address,address,address,address,uint24,bytes32)",
      [ethereum.Value.fromFixedBytes(id)],
    );

    return new PoolManager__poolIdToPoolKeyResult(
      result[0].toAddress(),
      result[1].toAddress(),
      result[2].toAddress(),
      result[3].toAddress(),
      result[4].toI32(),
      result[5].toBytes(),
    );
  }

  try_poolIdToPoolKey(
    id: Bytes,
  ): ethereum.CallResult<PoolManager__poolIdToPoolKeyResult> {
    let result = super.tryCall(
      "poolIdToPoolKey",
      "poolIdToPoolKey(bytes32):(address,address,address,address,uint24,bytes32)",
      [ethereum.Value.fromFixedBytes(id)],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      new PoolManager__poolIdToPoolKeyResult(
        value[0].toAddress(),
        value[1].toAddress(),
        value[2].toAddress(),
        value[3].toAddress(),
        value[4].toI32(),
        value[5].toBytes(),
      ),
    );
  }

  protocolFeeController(): Address {
    let result = super.call(
      "protocolFeeController",
      "protocolFeeController():(address)",
      [],
    );

    return result[0].toAddress();
  }

  try_protocolFeeController(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "protocolFeeController",
      "protocolFeeController():(address)",
      [],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  protocolFeesAccrued(currency: Address): BigInt {
    let result = super.call(
      "protocolFeesAccrued",
      "protocolFeesAccrued(address):(uint256)",
      [ethereum.Value.fromAddress(currency)],
    );

    return result[0].toBigInt();
  }

  try_protocolFeesAccrued(currency: Address): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "protocolFeesAccrued",
      "protocolFeesAccrued(address):(uint256)",
      [ethereum.Value.fromAddress(currency)],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  swap(
    key: PoolManager__swapInputKeyStruct,
    params: PoolManager__swapInputParamsStruct,
    hookData: Bytes,
  ): BigInt {
    let result = super.call(
      "swap",
      "swap((address,address,address,address,uint24,bytes32),(bool,int256,uint160),bytes):(int256)",
      [
        ethereum.Value.fromTuple(key),
        ethereum.Value.fromTuple(params),
        ethereum.Value.fromBytes(hookData),
      ],
    );

    return result[0].toBigInt();
  }

  try_swap(
    key: PoolManager__swapInputKeyStruct,
    params: PoolManager__swapInputParamsStruct,
    hookData: Bytes,
  ): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "swap",
      "swap((address,address,address,address,uint24,bytes32),(bool,int256,uint160),bytes):(int256)",
      [
        ethereum.Value.fromTuple(key),
        ethereum.Value.fromTuple(params),
        ethereum.Value.fromBytes(hookData),
      ],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  vault(): Address {
    let result = super.call("vault", "vault():(address)", []);

    return result[0].toAddress();
  }

  try_vault(): ethereum.CallResult<Address> {
    let result = super.tryCall("vault", "vault():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }
}

export class ConstructorCall extends ethereum.Call {
  get inputs(): ConstructorCall__Inputs {
    return new ConstructorCall__Inputs(this);
  }

  get outputs(): ConstructorCall__Outputs {
    return new ConstructorCall__Outputs(this);
  }
}

export class ConstructorCall__Inputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }

  get _vault(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class ConstructorCall__Outputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }
}

export class CollectProtocolFeesCall extends ethereum.Call {
  get inputs(): CollectProtocolFeesCall__Inputs {
    return new CollectProtocolFeesCall__Inputs(this);
  }

  get outputs(): CollectProtocolFeesCall__Outputs {
    return new CollectProtocolFeesCall__Outputs(this);
  }
}

export class CollectProtocolFeesCall__Inputs {
  _call: CollectProtocolFeesCall;

  constructor(call: CollectProtocolFeesCall) {
    this._call = call;
  }

  get recipient(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get currency(): Address {
    return this._call.inputValues[1].value.toAddress();
  }

  get amount(): BigInt {
    return this._call.inputValues[2].value.toBigInt();
  }
}

export class CollectProtocolFeesCall__Outputs {
  _call: CollectProtocolFeesCall;

  constructor(call: CollectProtocolFeesCall) {
    this._call = call;
  }

  get amountCollected(): BigInt {
    return this._call.outputValues[0].value.toBigInt();
  }
}

export class DonateCall extends ethereum.Call {
  get inputs(): DonateCall__Inputs {
    return new DonateCall__Inputs(this);
  }

  get outputs(): DonateCall__Outputs {
    return new DonateCall__Outputs(this);
  }
}

export class DonateCall__Inputs {
  _call: DonateCall;

  constructor(call: DonateCall) {
    this._call = call;
  }

  get key(): DonateCallKeyStruct {
    return changetype<DonateCallKeyStruct>(
      this._call.inputValues[0].value.toTuple(),
    );
  }

  get amount0(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }

  get amount1(): BigInt {
    return this._call.inputValues[2].value.toBigInt();
  }

  get hookData(): Bytes {
    return this._call.inputValues[3].value.toBytes();
  }
}

export class DonateCall__Outputs {
  _call: DonateCall;

  constructor(call: DonateCall) {
    this._call = call;
  }

  get delta(): BigInt {
    return this._call.outputValues[0].value.toBigInt();
  }
}

export class DonateCallKeyStruct extends ethereum.Tuple {
  get currency0(): Address {
    return this[0].toAddress();
  }

  get currency1(): Address {
    return this[1].toAddress();
  }

  get hooks(): Address {
    return this[2].toAddress();
  }

  get poolManager(): Address {
    return this[3].toAddress();
  }

  get fee(): i32 {
    return this[4].toI32();
  }

  get parameters(): Bytes {
    return this[5].toBytes();
  }
}

export class InitializeCall extends ethereum.Call {
  get inputs(): InitializeCall__Inputs {
    return new InitializeCall__Inputs(this);
  }

  get outputs(): InitializeCall__Outputs {
    return new InitializeCall__Outputs(this);
  }
}

export class InitializeCall__Inputs {
  _call: InitializeCall;

  constructor(call: InitializeCall) {
    this._call = call;
  }

  get key(): InitializeCallKeyStruct {
    return changetype<InitializeCallKeyStruct>(
      this._call.inputValues[0].value.toTuple(),
    );
  }

  get sqrtPriceX96(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }
}

export class InitializeCall__Outputs {
  _call: InitializeCall;

  constructor(call: InitializeCall) {
    this._call = call;
  }

  get tick(): i32 {
    return this._call.outputValues[0].value.toI32();
  }
}

export class InitializeCallKeyStruct extends ethereum.Tuple {
  get currency0(): Address {
    return this[0].toAddress();
  }

  get currency1(): Address {
    return this[1].toAddress();
  }

  get hooks(): Address {
    return this[2].toAddress();
  }

  get poolManager(): Address {
    return this[3].toAddress();
  }

  get fee(): i32 {
    return this[4].toI32();
  }

  get parameters(): Bytes {
    return this[5].toBytes();
  }
}

export class ModifyLiquidityCall extends ethereum.Call {
  get inputs(): ModifyLiquidityCall__Inputs {
    return new ModifyLiquidityCall__Inputs(this);
  }

  get outputs(): ModifyLiquidityCall__Outputs {
    return new ModifyLiquidityCall__Outputs(this);
  }
}

export class ModifyLiquidityCall__Inputs {
  _call: ModifyLiquidityCall;

  constructor(call: ModifyLiquidityCall) {
    this._call = call;
  }

  get key(): ModifyLiquidityCallKeyStruct {
    return changetype<ModifyLiquidityCallKeyStruct>(
      this._call.inputValues[0].value.toTuple(),
    );
  }

  get params(): ModifyLiquidityCallParamsStruct {
    return changetype<ModifyLiquidityCallParamsStruct>(
      this._call.inputValues[1].value.toTuple(),
    );
  }

  get hookData(): Bytes {
    return this._call.inputValues[2].value.toBytes();
  }
}

export class ModifyLiquidityCall__Outputs {
  _call: ModifyLiquidityCall;

  constructor(call: ModifyLiquidityCall) {
    this._call = call;
  }

  get delta(): BigInt {
    return this._call.outputValues[0].value.toBigInt();
  }

  get feeDelta(): BigInt {
    return this._call.outputValues[1].value.toBigInt();
  }
}

export class ModifyLiquidityCallKeyStruct extends ethereum.Tuple {
  get currency0(): Address {
    return this[0].toAddress();
  }

  get currency1(): Address {
    return this[1].toAddress();
  }

  get hooks(): Address {
    return this[2].toAddress();
  }

  get poolManager(): Address {
    return this[3].toAddress();
  }

  get fee(): i32 {
    return this[4].toI32();
  }

  get parameters(): Bytes {
    return this[5].toBytes();
  }
}

export class ModifyLiquidityCallParamsStruct extends ethereum.Tuple {
  get tickLower(): i32 {
    return this[0].toI32();
  }

  get tickUpper(): i32 {
    return this[1].toI32();
  }

  get liquidityDelta(): BigInt {
    return this[2].toBigInt();
  }

  get salt(): Bytes {
    return this[3].toBytes();
  }
}

export class PauseCall extends ethereum.Call {
  get inputs(): PauseCall__Inputs {
    return new PauseCall__Inputs(this);
  }

  get outputs(): PauseCall__Outputs {
    return new PauseCall__Outputs(this);
  }
}

export class PauseCall__Inputs {
  _call: PauseCall;

  constructor(call: PauseCall) {
    this._call = call;
  }
}

export class PauseCall__Outputs {
  _call: PauseCall;

  constructor(call: PauseCall) {
    this._call = call;
  }
}

export class SetProtocolFeeCall extends ethereum.Call {
  get inputs(): SetProtocolFeeCall__Inputs {
    return new SetProtocolFeeCall__Inputs(this);
  }

  get outputs(): SetProtocolFeeCall__Outputs {
    return new SetProtocolFeeCall__Outputs(this);
  }
}

export class SetProtocolFeeCall__Inputs {
  _call: SetProtocolFeeCall;

  constructor(call: SetProtocolFeeCall) {
    this._call = call;
  }

  get key(): SetProtocolFeeCallKeyStruct {
    return changetype<SetProtocolFeeCallKeyStruct>(
      this._call.inputValues[0].value.toTuple(),
    );
  }

  get newProtocolFee(): i32 {
    return this._call.inputValues[1].value.toI32();
  }
}

export class SetProtocolFeeCall__Outputs {
  _call: SetProtocolFeeCall;

  constructor(call: SetProtocolFeeCall) {
    this._call = call;
  }
}

export class SetProtocolFeeCallKeyStruct extends ethereum.Tuple {
  get currency0(): Address {
    return this[0].toAddress();
  }

  get currency1(): Address {
    return this[1].toAddress();
  }

  get hooks(): Address {
    return this[2].toAddress();
  }

  get poolManager(): Address {
    return this[3].toAddress();
  }

  get fee(): i32 {
    return this[4].toI32();
  }

  get parameters(): Bytes {
    return this[5].toBytes();
  }
}

export class SetProtocolFeeControllerCall extends ethereum.Call {
  get inputs(): SetProtocolFeeControllerCall__Inputs {
    return new SetProtocolFeeControllerCall__Inputs(this);
  }

  get outputs(): SetProtocolFeeControllerCall__Outputs {
    return new SetProtocolFeeControllerCall__Outputs(this);
  }
}

export class SetProtocolFeeControllerCall__Inputs {
  _call: SetProtocolFeeControllerCall;

  constructor(call: SetProtocolFeeControllerCall) {
    this._call = call;
  }

  get controller(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class SetProtocolFeeControllerCall__Outputs {
  _call: SetProtocolFeeControllerCall;

  constructor(call: SetProtocolFeeControllerCall) {
    this._call = call;
  }
}

export class SwapCall extends ethereum.Call {
  get inputs(): SwapCall__Inputs {
    return new SwapCall__Inputs(this);
  }

  get outputs(): SwapCall__Outputs {
    return new SwapCall__Outputs(this);
  }
}

export class SwapCall__Inputs {
  _call: SwapCall;

  constructor(call: SwapCall) {
    this._call = call;
  }

  get key(): SwapCallKeyStruct {
    return changetype<SwapCallKeyStruct>(
      this._call.inputValues[0].value.toTuple(),
    );
  }

  get params(): SwapCallParamsStruct {
    return changetype<SwapCallParamsStruct>(
      this._call.inputValues[1].value.toTuple(),
    );
  }

  get hookData(): Bytes {
    return this._call.inputValues[2].value.toBytes();
  }
}

export class SwapCall__Outputs {
  _call: SwapCall;

  constructor(call: SwapCall) {
    this._call = call;
  }

  get delta(): BigInt {
    return this._call.outputValues[0].value.toBigInt();
  }
}

export class SwapCallKeyStruct extends ethereum.Tuple {
  get currency0(): Address {
    return this[0].toAddress();
  }

  get currency1(): Address {
    return this[1].toAddress();
  }

  get hooks(): Address {
    return this[2].toAddress();
  }

  get poolManager(): Address {
    return this[3].toAddress();
  }

  get fee(): i32 {
    return this[4].toI32();
  }

  get parameters(): Bytes {
    return this[5].toBytes();
  }
}

export class SwapCallParamsStruct extends ethereum.Tuple {
  get zeroForOne(): boolean {
    return this[0].toBoolean();
  }

  get amountSpecified(): BigInt {
    return this[1].toBigInt();
  }

  get sqrtPriceLimitX96(): BigInt {
    return this[2].toBigInt();
  }
}

export class TransferOwnershipCall extends ethereum.Call {
  get inputs(): TransferOwnershipCall__Inputs {
    return new TransferOwnershipCall__Inputs(this);
  }

  get outputs(): TransferOwnershipCall__Outputs {
    return new TransferOwnershipCall__Outputs(this);
  }
}

export class TransferOwnershipCall__Inputs {
  _call: TransferOwnershipCall;

  constructor(call: TransferOwnershipCall) {
    this._call = call;
  }

  get newOwner(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class TransferOwnershipCall__Outputs {
  _call: TransferOwnershipCall;

  constructor(call: TransferOwnershipCall) {
    this._call = call;
  }
}

export class UnpauseCall extends ethereum.Call {
  get inputs(): UnpauseCall__Inputs {
    return new UnpauseCall__Inputs(this);
  }

  get outputs(): UnpauseCall__Outputs {
    return new UnpauseCall__Outputs(this);
  }
}

export class UnpauseCall__Inputs {
  _call: UnpauseCall;

  constructor(call: UnpauseCall) {
    this._call = call;
  }
}

export class UnpauseCall__Outputs {
  _call: UnpauseCall;

  constructor(call: UnpauseCall) {
    this._call = call;
  }
}

export class UpdateDynamicLPFeeCall extends ethereum.Call {
  get inputs(): UpdateDynamicLPFeeCall__Inputs {
    return new UpdateDynamicLPFeeCall__Inputs(this);
  }

  get outputs(): UpdateDynamicLPFeeCall__Outputs {
    return new UpdateDynamicLPFeeCall__Outputs(this);
  }
}

export class UpdateDynamicLPFeeCall__Inputs {
  _call: UpdateDynamicLPFeeCall;

  constructor(call: UpdateDynamicLPFeeCall) {
    this._call = call;
  }

  get key(): UpdateDynamicLPFeeCallKeyStruct {
    return changetype<UpdateDynamicLPFeeCallKeyStruct>(
      this._call.inputValues[0].value.toTuple(),
    );
  }

  get newDynamicLPFee(): i32 {
    return this._call.inputValues[1].value.toI32();
  }
}

export class UpdateDynamicLPFeeCall__Outputs {
  _call: UpdateDynamicLPFeeCall;

  constructor(call: UpdateDynamicLPFeeCall) {
    this._call = call;
  }
}

export class UpdateDynamicLPFeeCallKeyStruct extends ethereum.Tuple {
  get currency0(): Address {
    return this[0].toAddress();
  }

  get currency1(): Address {
    return this[1].toAddress();
  }

  get hooks(): Address {
    return this[2].toAddress();
  }

  get poolManager(): Address {
    return this[3].toAddress();
  }

  get fee(): i32 {
    return this[4].toI32();
  }

  get parameters(): Bytes {
    return this[5].toBytes();
  }
}
